version: "{build}"

platform: x64

branches:
  only:
    - master

clone_depth: 10

skip_tags: true

environment:
    GOPATH: c:\gopath
    APM_TEST_PACKAGES: 'environment go-config'

    matrix:
      - ATOM_CHANNEL: stable
      - ATOM_CHANNEL: beta

instsall:
  - go version
  - go env
  - mkdir c:\gopath
  - set PATH=%GOPATH%\bin;%PATH%
  - go get -u github.com/zmb3/gogetdoc
  - ps: Install-Product node 5

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
